name: Build and Push Docker

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: your-username/docker-build-action@main
      with:
        dockerfile: './Dockerfile'
        context: '.'
        tags: 'your-image-name:latest'
        push: 'true'
